### PR TITLE
fixed window close issue

### PR DESCRIPTION
**Pull request by JoeyHu4ng**
Removed the window close part since it is redundant
Add async wait for tabs.move()

### CODE REVIEW

**Review by kiasatina — CHANGES_REQUESTED** [review]
you might want to change the comment in line 272, i don't quite understand it

**Review by kiasatina — APPROVED** [review]
👍👍👍

**Review by sherry13131 — APPROVED** [review]
Looks good to me 👍

**Review by QiiLin — APPROVED** [review]
Good job

**Review by UOTLeop — APPROVED** [review]

**Pull request merged**
